/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.networknt.taiji.token;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Account extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -82418240323841175L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Account\",\"namespace\":\"com.networknt.taiji.token\",\"fields\":[{\"name\":\"balance\",\"type\":\"long\",\"doc\":\"current token balance for the symbol\",\"default\":0},{\"name\":\"approval\",\"type\":{\"type\":\"map\",\"values\":\"long\",\"avro.java.string\":\"String\"},\"doc\":\"approval from a token holder to withdraw\",\"default\":null},{\"name\":\"allowance\",\"type\":{\"type\":\"map\",\"values\":\"long\",\"avro.java.string\":\"String\"},\"doc\":\"allowance to the other address to withdraw\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Account> ENCODER =
      new BinaryMessageEncoder<Account>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Account> DECODER =
      new BinaryMessageDecoder<Account>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Account> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Account> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Account>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Account to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Account from a ByteBuffer. */
  public static Account fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** current token balance for the symbol */
  @Deprecated public long balance;
  /** approval from a token holder to withdraw */
  @Deprecated public java.util.Map<java.lang.String,java.lang.Long> approval;
  /** allowance to the other address to withdraw */
  @Deprecated public java.util.Map<java.lang.String,java.lang.Long> allowance;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Account() {}

  /**
   * All-args constructor.
   * @param balance current token balance for the symbol
   * @param approval approval from a token holder to withdraw
   * @param allowance allowance to the other address to withdraw
   */
  public Account(java.lang.Long balance, java.util.Map<java.lang.String,java.lang.Long> approval, java.util.Map<java.lang.String,java.lang.Long> allowance) {
    this.balance = balance;
    this.approval = approval;
    this.allowance = allowance;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return balance;
    case 1: return approval;
    case 2: return allowance;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: balance = (java.lang.Long)value$; break;
    case 1: approval = (java.util.Map<java.lang.String,java.lang.Long>)value$; break;
    case 2: allowance = (java.util.Map<java.lang.String,java.lang.Long>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'balance' field.
   * @return current token balance for the symbol
   */
  public java.lang.Long getBalance() {
    return balance;
  }

  /**
   * Sets the value of the 'balance' field.
   * current token balance for the symbol
   * @param value the value to set.
   */
  public void setBalance(java.lang.Long value) {
    this.balance = value;
  }

  /**
   * Gets the value of the 'approval' field.
   * @return approval from a token holder to withdraw
   */
  public java.util.Map<java.lang.String,java.lang.Long> getApproval() {
    return approval;
  }

  /**
   * Sets the value of the 'approval' field.
   * approval from a token holder to withdraw
   * @param value the value to set.
   */
  public void setApproval(java.util.Map<java.lang.String,java.lang.Long> value) {
    this.approval = value;
  }

  /**
   * Gets the value of the 'allowance' field.
   * @return allowance to the other address to withdraw
   */
  public java.util.Map<java.lang.String,java.lang.Long> getAllowance() {
    return allowance;
  }

  /**
   * Sets the value of the 'allowance' field.
   * allowance to the other address to withdraw
   * @param value the value to set.
   */
  public void setAllowance(java.util.Map<java.lang.String,java.lang.Long> value) {
    this.allowance = value;
  }

  /**
   * Creates a new Account RecordBuilder.
   * @return A new Account RecordBuilder
   */
  public static com.networknt.taiji.token.Account.Builder newBuilder() {
    return new com.networknt.taiji.token.Account.Builder();
  }

  /**
   * Creates a new Account RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Account RecordBuilder
   */
  public static com.networknt.taiji.token.Account.Builder newBuilder(com.networknt.taiji.token.Account.Builder other) {
    return new com.networknt.taiji.token.Account.Builder(other);
  }

  /**
   * Creates a new Account RecordBuilder by copying an existing Account instance.
   * @param other The existing instance to copy.
   * @return A new Account RecordBuilder
   */
  public static com.networknt.taiji.token.Account.Builder newBuilder(com.networknt.taiji.token.Account other) {
    return new com.networknt.taiji.token.Account.Builder(other);
  }

  /**
   * RecordBuilder for Account instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Account>
    implements org.apache.avro.data.RecordBuilder<Account> {

    /** current token balance for the symbol */
    private long balance;
    /** approval from a token holder to withdraw */
    private java.util.Map<java.lang.String,java.lang.Long> approval;
    /** allowance to the other address to withdraw */
    private java.util.Map<java.lang.String,java.lang.Long> allowance;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.networknt.taiji.token.Account.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.balance)) {
        this.balance = data().deepCopy(fields()[0].schema(), other.balance);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.approval)) {
        this.approval = data().deepCopy(fields()[1].schema(), other.approval);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.allowance)) {
        this.allowance = data().deepCopy(fields()[2].schema(), other.allowance);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Account instance
     * @param other The existing instance to copy.
     */
    private Builder(com.networknt.taiji.token.Account other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.balance)) {
        this.balance = data().deepCopy(fields()[0].schema(), other.balance);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.approval)) {
        this.approval = data().deepCopy(fields()[1].schema(), other.approval);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.allowance)) {
        this.allowance = data().deepCopy(fields()[2].schema(), other.allowance);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'balance' field.
      * current token balance for the symbol
      * @return The value.
      */
    public java.lang.Long getBalance() {
      return balance;
    }

    /**
      * Sets the value of the 'balance' field.
      * current token balance for the symbol
      * @param value The value of 'balance'.
      * @return This builder.
      */
    public com.networknt.taiji.token.Account.Builder setBalance(long value) {
      validate(fields()[0], value);
      this.balance = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'balance' field has been set.
      * current token balance for the symbol
      * @return True if the 'balance' field has been set, false otherwise.
      */
    public boolean hasBalance() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'balance' field.
      * current token balance for the symbol
      * @return This builder.
      */
    public com.networknt.taiji.token.Account.Builder clearBalance() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'approval' field.
      * approval from a token holder to withdraw
      * @return The value.
      */
    public java.util.Map<java.lang.String,java.lang.Long> getApproval() {
      return approval;
    }

    /**
      * Sets the value of the 'approval' field.
      * approval from a token holder to withdraw
      * @param value The value of 'approval'.
      * @return This builder.
      */
    public com.networknt.taiji.token.Account.Builder setApproval(java.util.Map<java.lang.String,java.lang.Long> value) {
      validate(fields()[1], value);
      this.approval = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'approval' field has been set.
      * approval from a token holder to withdraw
      * @return True if the 'approval' field has been set, false otherwise.
      */
    public boolean hasApproval() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'approval' field.
      * approval from a token holder to withdraw
      * @return This builder.
      */
    public com.networknt.taiji.token.Account.Builder clearApproval() {
      approval = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'allowance' field.
      * allowance to the other address to withdraw
      * @return The value.
      */
    public java.util.Map<java.lang.String,java.lang.Long> getAllowance() {
      return allowance;
    }

    /**
      * Sets the value of the 'allowance' field.
      * allowance to the other address to withdraw
      * @param value The value of 'allowance'.
      * @return This builder.
      */
    public com.networknt.taiji.token.Account.Builder setAllowance(java.util.Map<java.lang.String,java.lang.Long> value) {
      validate(fields()[2], value);
      this.allowance = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'allowance' field has been set.
      * allowance to the other address to withdraw
      * @return True if the 'allowance' field has been set, false otherwise.
      */
    public boolean hasAllowance() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'allowance' field.
      * allowance to the other address to withdraw
      * @return This builder.
      */
    public com.networknt.taiji.token.Account.Builder clearAllowance() {
      allowance = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Account build() {
      try {
        Account record = new Account();
        record.balance = fieldSetFlags()[0] ? this.balance : (java.lang.Long) defaultValue(fields()[0]);
        record.approval = fieldSetFlags()[1] ? this.approval : (java.util.Map<java.lang.String,java.lang.Long>) defaultValue(fields()[1]);
        record.allowance = fieldSetFlags()[2] ? this.allowance : (java.util.Map<java.lang.String,java.lang.Long>) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Account>
    WRITER$ = (org.apache.avro.io.DatumWriter<Account>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Account>
    READER$ = (org.apache.avro.io.DatumReader<Account>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
