/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.networknt.taiji.token;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum TokenTranType {
  T, A  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TokenTranType\",\"namespace\":\"com.networknt.taiji.token\",\"symbols\":[\"T\",\"A\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
