/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.networknt.taiji.kyc;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum KycType {
  P, B  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"KycType\",\"namespace\":\"com.networknt.taiji.kyc\",\"symbols\":[\"P\",\"B\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
