/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.networknt.taiji.kyc;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class KycVerifiedEvent extends org.apache.avro.specific.SpecificRecordBase implements KycEvent {
  private static final long serialVersionUID = -3839535249283387898L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"KycVerifiedEvent\",\"namespace\":\"com.networknt.taiji.kyc\",\"fields\":[{\"name\":\"EventId\",\"type\":{\"type\":\"record\",\"name\":\"EventId\",\"namespace\":\"com.networknt.taiji.event\",\"fields\":[{\"name\":\"address\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"owner address that create the token\"},{\"name\":\"nonce\",\"type\":\"long\",\"doc\":\"the number of the transactions for the address\"}]}},{\"name\":\"timestamp\",\"type\":\"long\",\"doc\":\"time the event is recorded on the blockchain\",\"default\":0},{\"name\":\"offset\",\"type\":\"long\",\"doc\":\"kafka partition offset\",\"default\":0},{\"name\":\"partition\",\"type\":\"int\",\"doc\":\"kafka partition id\",\"default\":0}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<KycVerifiedEvent> ENCODER =
      new BinaryMessageEncoder<KycVerifiedEvent>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<KycVerifiedEvent> DECODER =
      new BinaryMessageDecoder<KycVerifiedEvent>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<KycVerifiedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<KycVerifiedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<KycVerifiedEvent>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this KycVerifiedEvent to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a KycVerifiedEvent from a ByteBuffer. */
  public static KycVerifiedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public com.networknt.taiji.event.EventId EventId;
  /** time the event is recorded on the blockchain */
  @Deprecated public long timestamp;
  /** kafka partition offset */
  @Deprecated public long offset;
  /** kafka partition id */
  @Deprecated public int partition;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public KycVerifiedEvent() {}

  /**
   * All-args constructor.
   * @param EventId The new value for EventId
   * @param timestamp time the event is recorded on the blockchain
   * @param offset kafka partition offset
   * @param partition kafka partition id
   */
  public KycVerifiedEvent(com.networknt.taiji.event.EventId EventId, java.lang.Long timestamp, java.lang.Long offset, java.lang.Integer partition) {
    this.EventId = EventId;
    this.timestamp = timestamp;
    this.offset = offset;
    this.partition = partition;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return EventId;
    case 1: return timestamp;
    case 2: return offset;
    case 3: return partition;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: EventId = (com.networknt.taiji.event.EventId)value$; break;
    case 1: timestamp = (java.lang.Long)value$; break;
    case 2: offset = (java.lang.Long)value$; break;
    case 3: partition = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'EventId' field.
   * @return The value of the 'EventId' field.
   */
  public com.networknt.taiji.event.EventId getEventId() {
    return EventId;
  }

  /**
   * Sets the value of the 'EventId' field.
   * @param value the value to set.
   */
  public void setEventId(com.networknt.taiji.event.EventId value) {
    this.EventId = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return time the event is recorded on the blockchain
   */
  public java.lang.Long getTimestamp() {
    return timestamp;
  }

  /**
   * Sets the value of the 'timestamp' field.
   * time the event is recorded on the blockchain
   * @param value the value to set.
   */
  public void setTimestamp(java.lang.Long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'offset' field.
   * @return kafka partition offset
   */
  public java.lang.Long getOffset() {
    return offset;
  }

  /**
   * Sets the value of the 'offset' field.
   * kafka partition offset
   * @param value the value to set.
   */
  public void setOffset(java.lang.Long value) {
    this.offset = value;
  }

  /**
   * Gets the value of the 'partition' field.
   * @return kafka partition id
   */
  public java.lang.Integer getPartition() {
    return partition;
  }

  /**
   * Sets the value of the 'partition' field.
   * kafka partition id
   * @param value the value to set.
   */
  public void setPartition(java.lang.Integer value) {
    this.partition = value;
  }

  /**
   * Creates a new KycVerifiedEvent RecordBuilder.
   * @return A new KycVerifiedEvent RecordBuilder
   */
  public static com.networknt.taiji.kyc.KycVerifiedEvent.Builder newBuilder() {
    return new com.networknt.taiji.kyc.KycVerifiedEvent.Builder();
  }

  /**
   * Creates a new KycVerifiedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new KycVerifiedEvent RecordBuilder
   */
  public static com.networknt.taiji.kyc.KycVerifiedEvent.Builder newBuilder(com.networknt.taiji.kyc.KycVerifiedEvent.Builder other) {
    return new com.networknt.taiji.kyc.KycVerifiedEvent.Builder(other);
  }

  /**
   * Creates a new KycVerifiedEvent RecordBuilder by copying an existing KycVerifiedEvent instance.
   * @param other The existing instance to copy.
   * @return A new KycVerifiedEvent RecordBuilder
   */
  public static com.networknt.taiji.kyc.KycVerifiedEvent.Builder newBuilder(com.networknt.taiji.kyc.KycVerifiedEvent other) {
    return new com.networknt.taiji.kyc.KycVerifiedEvent.Builder(other);
  }

  /**
   * RecordBuilder for KycVerifiedEvent instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<KycVerifiedEvent>
    implements org.apache.avro.data.RecordBuilder<KycVerifiedEvent> {

    private com.networknt.taiji.event.EventId EventId;
    private com.networknt.taiji.event.EventId.Builder EventIdBuilder;
    /** time the event is recorded on the blockchain */
    private long timestamp;
    /** kafka partition offset */
    private long offset;
    /** kafka partition id */
    private int partition;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.networknt.taiji.kyc.KycVerifiedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.EventId)) {
        this.EventId = data().deepCopy(fields()[0].schema(), other.EventId);
        fieldSetFlags()[0] = true;
      }
      if (other.hasEventIdBuilder()) {
        this.EventIdBuilder = com.networknt.taiji.event.EventId.newBuilder(other.getEventIdBuilder());
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.offset)) {
        this.offset = data().deepCopy(fields()[2].schema(), other.offset);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.partition)) {
        this.partition = data().deepCopy(fields()[3].schema(), other.partition);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing KycVerifiedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.networknt.taiji.kyc.KycVerifiedEvent other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.EventId)) {
        this.EventId = data().deepCopy(fields()[0].schema(), other.EventId);
        fieldSetFlags()[0] = true;
      }
      this.EventIdBuilder = null;
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.offset)) {
        this.offset = data().deepCopy(fields()[2].schema(), other.offset);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.partition)) {
        this.partition = data().deepCopy(fields()[3].schema(), other.partition);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'EventId' field.
      * @return The value.
      */
    public com.networknt.taiji.event.EventId getEventId() {
      return EventId;
    }

    /**
      * Sets the value of the 'EventId' field.
      * @param value The value of 'EventId'.
      * @return This builder.
      */
    public com.networknt.taiji.kyc.KycVerifiedEvent.Builder setEventId(com.networknt.taiji.event.EventId value) {
      validate(fields()[0], value);
      this.EventIdBuilder = null;
      this.EventId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'EventId' field has been set.
      * @return True if the 'EventId' field has been set, false otherwise.
      */
    public boolean hasEventId() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'EventId' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.networknt.taiji.event.EventId.Builder getEventIdBuilder() {
      if (EventIdBuilder == null) {
        if (hasEventId()) {
          setEventIdBuilder(com.networknt.taiji.event.EventId.newBuilder(EventId));
        } else {
          setEventIdBuilder(com.networknt.taiji.event.EventId.newBuilder());
        }
      }
      return EventIdBuilder;
    }

    /**
     * Sets the Builder instance for the 'EventId' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public com.networknt.taiji.kyc.KycVerifiedEvent.Builder setEventIdBuilder(com.networknt.taiji.event.EventId.Builder value) {
      clearEventId();
      EventIdBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'EventId' field has an active Builder instance
     * @return True if the 'EventId' field has an active Builder instance
     */
    public boolean hasEventIdBuilder() {
      return EventIdBuilder != null;
    }

    /**
      * Clears the value of the 'EventId' field.
      * @return This builder.
      */
    public com.networknt.taiji.kyc.KycVerifiedEvent.Builder clearEventId() {
      EventId = null;
      EventIdBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * time the event is recorded on the blockchain
      * @return The value.
      */
    public java.lang.Long getTimestamp() {
      return timestamp;
    }

    /**
      * Sets the value of the 'timestamp' field.
      * time the event is recorded on the blockchain
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public com.networknt.taiji.kyc.KycVerifiedEvent.Builder setTimestamp(long value) {
      validate(fields()[1], value);
      this.timestamp = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * time the event is recorded on the blockchain
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * time the event is recorded on the blockchain
      * @return This builder.
      */
    public com.networknt.taiji.kyc.KycVerifiedEvent.Builder clearTimestamp() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'offset' field.
      * kafka partition offset
      * @return The value.
      */
    public java.lang.Long getOffset() {
      return offset;
    }

    /**
      * Sets the value of the 'offset' field.
      * kafka partition offset
      * @param value The value of 'offset'.
      * @return This builder.
      */
    public com.networknt.taiji.kyc.KycVerifiedEvent.Builder setOffset(long value) {
      validate(fields()[2], value);
      this.offset = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'offset' field has been set.
      * kafka partition offset
      * @return True if the 'offset' field has been set, false otherwise.
      */
    public boolean hasOffset() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'offset' field.
      * kafka partition offset
      * @return This builder.
      */
    public com.networknt.taiji.kyc.KycVerifiedEvent.Builder clearOffset() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'partition' field.
      * kafka partition id
      * @return The value.
      */
    public java.lang.Integer getPartition() {
      return partition;
    }

    /**
      * Sets the value of the 'partition' field.
      * kafka partition id
      * @param value The value of 'partition'.
      * @return This builder.
      */
    public com.networknt.taiji.kyc.KycVerifiedEvent.Builder setPartition(int value) {
      validate(fields()[3], value);
      this.partition = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'partition' field has been set.
      * kafka partition id
      * @return True if the 'partition' field has been set, false otherwise.
      */
    public boolean hasPartition() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'partition' field.
      * kafka partition id
      * @return This builder.
      */
    public com.networknt.taiji.kyc.KycVerifiedEvent.Builder clearPartition() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public KycVerifiedEvent build() {
      try {
        KycVerifiedEvent record = new KycVerifiedEvent();
        if (EventIdBuilder != null) {
          record.EventId = this.EventIdBuilder.build();
        } else {
          record.EventId = fieldSetFlags()[0] ? this.EventId : (com.networknt.taiji.event.EventId) defaultValue(fields()[0]);
        }
        record.timestamp = fieldSetFlags()[1] ? this.timestamp : (java.lang.Long) defaultValue(fields()[1]);
        record.offset = fieldSetFlags()[2] ? this.offset : (java.lang.Long) defaultValue(fields()[2]);
        record.partition = fieldSetFlags()[3] ? this.partition : (java.lang.Integer) defaultValue(fields()[3]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<KycVerifiedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<KycVerifiedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<KycVerifiedEvent>
    READER$ = (org.apache.avro.io.DatumReader<KycVerifiedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
